### ISSUE TITLE
Jimple file is error

### ISSUE THREAD

**Issue by slimming-fat** [soot-oss/SootUp#800] opened 2024-01-08 08:47 UTC
I used sootUp to convert.class files to jimple files, but found that the converted jimple had problems.
The decompiled bytecodeis as follows:
![image](https://github.com/soot-oss/SootUp/assets/126549527/72d7ac85-89bc-40c1-ae60-4f826653eb34)
The converted jimple is as follows:
![image](https://github.com/soot-oss/SootUp/assets/126549527/fe4d5104-556e-409c-a88d-2d6fb9da767a)
Due to missing statements in jimple
```java 
selectPathInterfaceImpl=$stack30
```
This causes  **selectPathInterfaceImpl ==null**, which is an error. But, the jimple file generated by **Soot** is fine. The converted jimple is as follows:
![image](https://github.com/soot-oss/SootUp/assets/126549527/06d10d10-be5e-44ec-b4e0-fb8c0e16f955)

**Comment by swissiety** [comment] 2024-01-08 09:00
Hi @slimming-fat
which version of sootup do you use?

**summary:** the problem is staticInvoke result gets assigned to $stack30 instead of selectPathInterfaceImpl.

**Comment by slimming-fat** [comment] 2024-01-08 09:02
> Hi @slimming-fat which version of sootup do you use?
> 
> **summary:** the problem is staticInvoke result gets assigned to $stack30 instead of selectPathInterfaceImpl.

Hi, I use sootUp v1.1.2
In the converted jimple, **$stack30** appears only twice, once as an accepting variable in the staticinvoke statement and once as an initialization statement.

**Comment by swissiety** [comment] 2024-01-08 09:08
ok, we adapted something according to those assignments in the develop branch that hopefully fixed this problem as well - please checkout the latest version of the develop branch (you can use [jitpack](https://jitpack.io/#soot-oss/SootUp/develop-SNAPSHOT) to add the develop branch to your project) and have a look if this still occurs.
you may need to adapt the setup as we removed the *-`Project` datastructure and moved its parameters directly into the *-`View`

**Comment by slimming-fat** [comment] 2024-01-08 09:10
Ok, I'll try.

**Comment by JonasKlauke** [comment] 2024-01-08 11:17
I wonder, what is our solution for the two different switch statements in the old soot?

**Comment by slimming-fat** [comment] 2024-01-08 11:48
> ok, we adapted something according to those assignments in the develop branch that hopefully fixed this problem as well - please checkout the latest version of the develop branch (you can use [jitpack](https://jitpack.io/#soot-oss/SootUp/develop-SNAPSHOT) to add the develop branch to your project) and have a look if this still occurs. you may need to adapt the setup as we removed the *-`Project` datastructure and moved its parameters directly into the *-`View`

Hi @swissiety
Thank you very much for your advice! I don't have this issue with sootUp develop, and here are the results:
![image](https://github.com/soot-oss/SootUp/assets/126549527/45a94f6b-4fb6-4b6d-a34f-9ef6b1ee0a97)
I would appreciate a quick release of this version!

**Closed as completed** 2024-01-08 11:55 UTC
