### ISSUE TITLE
SootUp fat jar issues

### ISSUE THREAD

**Issue by lehvolk** [soot-oss/SootUp#575] opened 2023-04-04 12:38 UTC
It seems that SootUp jar files is a fat jars. It brings jar hell because gradle/maven can't handle transitive dependencies correctly.

Possible solutions:
- add transitive maven/gradle dependency and remove fat jar distribution
- repackage Guava, ASM etc with package prefix like sootup.com.google.*

**Comment by jpstotz** [comment] 2023-04-04 13:42
Duplicate of #560

**Comment by JonasKlauke** [comment] 2023-04-04 14:14
closed because it is a duplicate of #560

**Closed as completed by JonasKlauke** 2023-04-04 14:14 UTC
